name: expiration-test

on:
  pull_request:
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && npm i && npm run test:ci
