name: pay-test

on:
  pull_request:
    paths:
      - "pay/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pay && npm i && npm run test:ci
